# Generated by Django 3.1.4 on 2020-12-26 10:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_auto_20201225_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=None, max_length=150)),
                ('bvn', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='moneydeposit',
            old_name='enter_your_user_name',
            new_name='bank_name',
        ),
        migrations.RemoveField(
            model_name='moneydeposit',
            name='enter_the_destination_account_number',
        ),
        migrations.AddField(
            model_name='moneydeposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneydeposit',
            name='orginator_name',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AddField(
            model_name='moneydeposit',
            name='payment_reference',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='moneydeposit',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fundreceiver', to='escrow.wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='escrow.profile'),
        ),
        migrations.AlterField(
            model_name='moneydeposit',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
