# Generated by Django 3.1.4 on 2021-04-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0005_auto_20210404_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this wallet should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='virtualwallet',
            field=models.IntegerField(null=True),
        ),
    ]
