# Generated by Django 3.1.4 on 2021-04-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0007_auto_20210405_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='virtualwallet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
