# Generated by Django 3.1.4 on 2021-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0008_auto_20210405_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
