# Generated by Django 3.1.4 on 2021-04-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0009_auto_20210405_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendcoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default=None, max_length=150)),
                ('receiver', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this wallet should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
