# Generated by Django 3.1.4 on 2021-04-09 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0011_auto_20210409_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcoins',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rexeiver', to='escrow.profile'),
        ),
        migrations.AlterField(
            model_name='sendcoins',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xender', to='escrow.profile'),
        ),
    ]
