# Generated by Django 3.1.4 on 2021-04-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0012_auto_20210409_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sendcoins',
            new_name='sendcoin',
        ),
    ]
