# Generated by Django 3.1.4 on 2021-04-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0015_auto_20210409_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcoin',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escrow.profile'),
        ),
    ]
