# Generated by Django 3.1.4 on 2021-04-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0016_auto_20210409_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcoin',
            name='receiver',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='sendcoin',
            name='sender',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
