# Generated by Django 3.1.4 on 2021-04-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0017_auto_20210410_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendcoin',
            name='wallet',
        ),
    ]
