# Generated by Django 3.1.4 on 2021-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0018_remove_sendcoin_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('transaction_type', models.CharField(max_length=20)),
                ('narration', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('transaction_ref', models.CharField(max_length=35)),
                ('flw_ref', models.CharField(max_length=35)),
                ('created_at', models.CharField(max_length=26)),
            ],
        ),
    ]
