# Generated by Django 3.1.4 on 2021-04-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0019_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='narration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
