# Generated by Django 3.1.4 on 2021-04-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0021_auto_20210414_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='customer_email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='log',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
